server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:smartdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: verysecretkey_for_demo_change_in_prod
  expirationMs: 3600000
