server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: metadata-service
          uri: lb://document-metadata-service
          predicates:
            - Path=/api/metadata/**
        - id: file-storage-service
          uri: lb://file-storage-service
          predicates:
            - Path=/api/files/**
